import { buildEditarraExportPayload } from './exportPayloadModel';

const buildInput = () => ({
  selectedSite: {
    id: 'site-a',
    name: 'EDITARRA',
    domain: 'www.licitometro.ar/editarra',
    cadence: '3 notas/dia',
    approval: 'asistido',
    seoMode: 'umsa-diaria',
  },
  selectedRecipe: {
    id: 'reactiva',
    label: 'Nota reactiva',
    shortLabel: 'Reactiva',
    category: 'noticias',
    publishAt: '07:00',
    defaultDepth: 'Alta',
    defaultTokens: 10500,
    intent: 'explicar novedad',
    sourcePlan: 'fuentes primarias',
    variableKeys: ['keyword_principal'],
  },
  selectedOperationMode: {
    id: 'modo-alerta',
    name: 'Alerta',
    shortLabel: 'Alerta',
    intent: 'reaccionar con evidencia',
    recipeId: 'reactiva',
    authorName: 'Editor UMSA Diaria',
    profilePatch: {
      sourceMinimum: 4,
      postingMode: 'asistido',
      tone: 'directo',
      guardrails: [],
    },
    authorPatch: {
      voiceBrief: 'voz tecnica',
      influenceMode: 'documental',
    },
    variables: [],
  },
  operationModes: [],
  profiles: [],
  selectedWorkflowProfile: {
    id: 'profile-a',
    name: 'UMSA Diaria',
    site: 'www.licitometro.ar/editarra',
    model: 'umsa-diaria',
    cadence: '3 notas/dia',
    defaultAuthor: 'Editor UMSA Diaria',
    sourceMinimum: 4,
    endpoint: 'https://cms.local/api/blog',
    postingMode: 'asistido',
    tone: 'tecnico',
    guardrails: [],
  },
  authors: [
    {
      id: 'author-a',
      name: 'Editor UMSA Diaria',
      role: 'editor',
      active: true,
      models: 'umsa',
      tone: ['claro'],
      banned: ['humo'],
      mix: 'reactiva',
      score: 90,
      voiceBrief: 'preciso',
      register: 'profesional',
      rhythm: 'medio',
      stance: 'evidencia',
      density: 'alta',
      locality: 'AR',
      influenceMode: 'adherir',
      references: ['documentacion oficial'],
      antiReferences: ['gacetilla'],
      styleWeights: { claridad: 5, evidencia: 5, opinion: 1, humanidad: 3, seo: 4 },
      influences: [],
    },
  ],
  topicTokenBudget: 37000,
  packageFileKeys: ['article.md', 'publication_payload.json'],
  activeProfileRuntime: { id: 'runtime-a' },
  guidedRunStages: [{ id: 'agenda', status: 'listo' }],
  visibleNoteVariables: [{ key: 'keyword_principal', value: 'datos abiertos', enabled: true, description: 'keyword', source: 'perfil' }],
  selectedGuidedRunRecords: Array.from({ length: 10 }, (_, index) => ({ id: `run-${index}`, topicId: 'topic-a' })),
  operationalWorkspace: { readiness: { status: 'listo' } },
  operationalContract: { id: 'contract-a' },
  automationRecipe: { id: 'recipe-a' },
  editorialAgendas: [
    {
      id: 'agenda-a',
      name: 'Agenda abierta',
      destination: 'UMSA Blog',
      audience: 'pymes',
      compatibleAuthors: ['Editor UMSA Diaria'],
      compatibleRecipes: ['reactiva'],
      compatibleOperationModes: ['modo-alerta'],
      interests: ['datos abiertos'],
      tropesToSeek: ['norma nueva'],
      tropesToAvoid: ['opinion sin fuente'],
      sourceUrls: ['https://example.com/feed'],
      publishingSlots: ['07:00'],
      scoringWeights: { interest: 10, trope: 10, source: 10, avoidPenalty: 20 },
      createdAt: '2026-01-01',
      updatedAt: '2026-01-02',
    },
  ],
  discoveryRuns: [
    {
      id: 'discovery-a',
      agendaId: 'agenda-a',
      query: 'datos abiertos',
      urls: ['https://example.com/feed'],
      status: 'completo',
      sourceCount: 1,
      candidateCount: 1,
      warnings: [],
      createdAt: '2026-01-01',
      completedAt: '2026-01-01',
    },
  ],
  discoveryCandidates: [
    {
      id: 'candidate-a',
      runId: 'discovery-a',
      agendaId: 'agenda-a',
      title: 'Nueva fuente abierta',
      summary: 'Resumen',
      sourceName: 'Example',
      sourceUrl: 'https://example.com/news',
      snippet: 'Evidencia',
      detectedTrope: 'norma nueva',
      matchedInterests: ['datos abiertos'],
      recommendedAuthor: 'Editor UMSA Diaria',
      recommendedRecipeId: 'reactiva',
      recommendedOperationModeId: 'modo-alerta',
      score: 78,
      warnings: [],
      status: 'descubierto',
      createdAt: '2026-01-01',
      updatedAt: '2026-01-01',
    },
  ],
  missionPresets: [],
  activeNoteRun: { id: 'note-run-a' },
  aiHandoff: { id: 'handoff-a' },
  aiRunRequest: { id: 'ai-request-a' },
  publicationManifest: { id: 'publication-a', status: 'revision', activePayload: { title: 'Tema A' } },
  publicationDestinations: [{ id: 'umsa-blog', name: 'UMSA Blog' }],
  publicationTargets: [{ destinationId: 'umsa-blog', status: 'preview_listo' }],
  activePipelineState: {
    status: 'operando',
    progress: 80,
    currentStageId: 'payload',
    nextControl: 'Publicar',
    blockers: [],
    stages: [],
    actions: [],
  },
  activeRadarRunReport: { id: 'radar-report-a' },
  activeNoteProposal: { id: 'proposal-a' },
  activePublicExportBundle: { id: 'bundle-a', readyToPublish: true },
  activeImageProductionPrompt: '# Prompt de imagen',
  editorialPackage: {
    aiBrief: { title: 'Brief' },
    publicationPayload: {
      titulo: 'Tema A',
      contenido: 'Contenido listo',
      slug: 'tema-a',
    },
    qualityAudit: { status: 'aprobado' },
    imageManifest: { id: 'image-manifest-a', status: 'prompt_listo' },
  },
  selectedTopic: {
    id: 'topic-a',
    title: 'Tema A',
    status: 'aprobado',
    priority: 1,
    depth: 'Alta',
    tokens: 10500,
    author: 'Editor UMSA Diaria',
    source: 'fuente primaria',
    narrative: 'narrativa',
    seo: 'seo',
    publishAt: '07:00',
    agendaId: 'agenda-a',
    candidateId: 'candidate-a',
    destinationProfileId: 'profile-a',
    recipeId: 'reactiva',
    operationModeId: 'modo-alerta',
    trope: 'norma nueva',
    interests: ['datos abiertos'],
    discoverySourceUrl: 'https://example.com/news',
  },
  currentDraftStatus: 'aprobado',
  validatedEvidenceCount: 4,
  guidedNextStepLabel: 'Publicar',
  dailyBatchControl: {
    active: true,
    topicIds: ['topic-a', 'topic-b'],
    topicCount: 2,
    validated: 5,
    pendingGuided: 1,
    sourceMinimum: 8,
    aiReady: 1,
    auditApproved: 1,
    payloadReady: 1,
    latestTitles: ['Tema A'],
  },
  topics: [
    {
      id: 'topic-a',
      title: 'Tema A',
      status: 'aprobado',
      priority: 1,
      depth: 'Alta',
      tokens: 10500,
      author: 'Editor UMSA Diaria',
      source: 'fuente primaria',
      narrative: 'narrativa',
      seo: 'seo',
      publishAt: '07:00',
    },
    {
      id: 'topic-b',
      title: 'Tema B',
      status: 'redaccion',
      priority: 2,
      depth: 'Media',
      tokens: 8000,
      author: 'Editor UMSA Diaria',
      source: 'fuente secundaria',
      narrative: 'narrativa',
      seo: 'seo',
      publishAt: '12:00',
    },
    {
      id: 'topic-descartado',
      title: 'No exportar',
      status: 'descartado',
      priority: 9,
      depth: 'Breve',
      tokens: 3000,
      author: 'Editor',
      source: 'sin fuente',
      narrative: 'no',
      seo: 'no',
      publishAt: 'no',
    },
  ],
  drafts: [
    {
      id: 'draft-a',
      topicId: 'topic-a',
      variant: 'base',
      status: 'aprobado',
      title: 'Tema A',
      seoTitle: 'Tema A SEO',
      body: 'Body',
      notes: 'Notes',
      updatedAt: '2026-01-01',
    },
  ],
  evidence: [
    {
      id: 'evidence-a',
      topicId: 'topic-a',
      sourceName: 'Example',
      sourceUrl: 'https://example.com/news',
      claim: 'Claim',
      status: 'validado',
      confidence: 90,
      notes: 'ok',
    },
  ],
  getDailyBatchRecipeId: (topicId: string) => topicId === 'topic-b' ? 'caso' : 'reactiva',
  noteVariableOverrides: [{ id: 'override-a', topicId: 'topic-a', recipeId: 'reactiva', key: 'keyword', value: 'datos', description: 'desc', enabled: true }],
  workflowVariables: [{ id: 'var-a', key: 'keyword', value: 'datos', scope: 'seo', description: 'desc', enabled: true }],
  editorRules: [{ id: 'rule-a', title: 'Regla', body: 'Body', enabled: true }],
  imagePrompts: [{ id: 'image-a', title: 'Imagen', ratio: '16:9', status: 'prompt_listo', prompt: 'Prompt' }],
  reusableImages: ['image-a'],
  seoExperiments: [{ id: 'seo-a', topicId: 'topic-a', title: 'SEO', description: 'Descripcion', focusKeyword: 'datos', strategy: 'Mixto', ctr: 1, impressions: 10, selected: true, notes: 'nota' }],
  analyticsRecords: [{ id: 'analytics-a', topicId: 'topic-a', period: '2026-01', trafficSource: 'organico', visits: 100, averageReadSeconds: 40, ctaClicks: 2, shares: 1, comments: 0, conversionRate: 1.2, successCriteria: 'lectura', performanceScore: 80, learningNote: 'ok' }],
  draftVersions: [{ id: 'version-a', topicId: 'topic-a', draftId: 'draft-a', version: 1, variant: 'base', status: 'aprobado', title: 'Tema A', seoTitle: 'Tema A SEO', body: 'Body', notes: 'Notes', changeNote: 'Cambio', snapshotAt: '2026-01-01', authorName: 'Editor' }],
  auditEvents: [{ id: 'audit-a', event: 'Exportado', detail: 'Detalle', time: '10:00' }],
  guidedRunRecords: [{ id: 'guided-a', topicId: 'topic-a', recipeId: 'reactiva', profileId: 'profile-a', status: 'completo', steps: ['agenda'], nextControl: 'Publicar', summary: 'ok', time: '10:00' }],
  distributionPlanManifest: { id: 'distribution-a', items: [] },
  distributionActions: { 'topic-a:web': 'copiado' },
} as any);

describe('buildEditarraExportPayload', () => {
  it('builds the portable package contract without enabling external posting', () => {
    const payload = buildEditarraExportPayload(buildInput());

    expect(payload).toMatchObject({
      product: 'editarra',
      standalone: true,
      host_url: 'www.licitometro.ar/editarra',
      route: '/editarra',
      workflow: {
        external_post_enabled: false,
        outputs: ['article.md', 'publication_payload.json'],
      },
      active_note_pipeline: {
        topic_id: 'topic-a',
        payload_ready: true,
        ready_for_payload: true,
        quality_status: 'aprobado',
      },
      publication_targets: [{ destinationId: 'umsa-blog', status: 'preview_listo' }],
      active_image_prompt_markdown: '# Prompt de imagen',
    });
  });

  it('serializes agendas, runs and candidates with stable snake_case keys', () => {
    const payload = buildEditarraExportPayload(buildInput());

    expect(payload.editorial_agendas[0]).toMatchObject({
      id: 'agenda-a',
      source_urls: ['https://example.com/feed'],
      tropes_to_seek: ['norma nueva'],
      compatible_operation_modes: ['modo-alerta'],
    });
    expect(payload.discovery_runs[0]).toMatchObject({
      id: 'discovery-a',
      agenda_id: 'agenda-a',
      source_count: 1,
      candidate_count: 1,
    });
    expect(payload.discovery_candidates[0]).toMatchObject({
      id: 'candidate-a',
      source_url: 'https://example.com/news',
      recommended_operation_mode_id: 'modo-alerta',
    });
  });

  it('filters discarded topics and builds daily batch item readiness', () => {
    const payload = buildEditarraExportPayload(buildInput());

    expect(payload.topics.map((topic) => topic.id)).toEqual(['topic-a', 'topic-b']);
    expect(payload.active_daily_batch.items).toEqual([
      expect.objectContaining({
        topic_id: 'topic-a',
        title: 'Tema A',
        recipe_id: 'reactiva',
        draft_status: 'aprobado',
        evidence_validated: 1,
        ready_for_payload: true,
      }),
      expect.objectContaining({
        topic_id: 'topic-b',
        title: 'Tema B',
        recipe_id: 'caso',
        draft_status: 'sin_borrador',
        evidence_validated: 0,
        ready_for_payload: false,
      }),
    ]);
  });
});
