#!/bin/bash
# Generate Cloudflare configuration instructions for a preview PR

if [ -z "$1" ]; then
    echo "Usage: $0 <PR_NUMBER>"
    echo "Example: $0 42"
    exit 1
fi

PR=$1
PORT=$((8000 + PR))
HOSTNAME="pr-${PR}.dev.licitometro.ar"
VPS_IP="76.13.234.213"

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║  Cloudflare Configuration for PR #${PR}"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""
echo "📍 Preview Info:"
echo "   PR Number:  #${PR}"
echo "   Hostname:   ${HOSTNAME}"
echo "   Port:       ${PORT}"
echo "   VPS IP:     ${VPS_IP}"
echo ""
echo "════════════════════════════════════════════════════════════════"
echo "1️⃣  DNS A RECORD"
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "Cloudflare Dashboard → licitometro.ar → DNS → Add record"
echo ""
echo "  Type:     A"
echo "  Name:     pr-${PR}"
echo "  IPv4:     ${VPS_IP}"
echo "  Proxy:    ☁️  ON (orange cloud)"
echo "  TTL:      Auto"
echo ""
echo "════════════════════════════════════════════════════════════════"
echo "2️⃣  ORIGIN RULE (Port Override)"
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "Cloudflare Dashboard → Rules → Origin Rules → Create rule"
echo ""
echo "  Rule name: Preview PR #${PR} Port"
echo ""
echo "  When incoming requests match:"
echo "    Field:     Hostname"
echo "    Operator:  equals"
echo "    Value:     ${HOSTNAME}"
echo ""
echo "  Then:"
echo "    ☑ Destination Port"
echo "    Rewrite to: ${PORT}"
echo ""
echo "════════════════════════════════════════════════════════════════"
echo "3️⃣  CLOUDFLARE SSL/TLS MODE"
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "Cloudflare Dashboard → SSL/TLS → Overview"
echo ""
echo "  Mode: Flexible (recommended)"
echo "        or Full (if you want E2E encryption)"
echo ""
echo "════════════════════════════════════════════════════════════════"
echo "4️⃣  VERIFICATION TESTS"
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "# DNS Resolution (wait 1-2 min after creation):"
echo "dig ${HOSTNAME}"
echo ""
echo "# Direct access (works immediately):"
echo "curl http://${VPS_IP}:${PORT}/api/health"
echo ""
echo "# Domain access (after DNS configured):"
echo "curl https://${HOSTNAME}/api/health"
echo ""
echo "# Frontend (browser):"
echo "open https://${HOSTNAME}"
echo ""
echo "════════════════════════════════════════════════════════════════"
echo "5️⃣  PREVIEW URLS"
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "  Direct (works now):   http://${VPS_IP}:${PORT}"
echo "  Domain (needs DNS):   https://${HOSTNAME}"
echo ""
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "✅ Configuration complete! Test the URLs above."
echo ""
